export const chp1_race_description = [
  {
    id: "div_race1",
    type: "checkbox",
    raceName: "Ludzie",
    class: "race1 checkbox_container",
    availableProfessions: [
      { profName: "WOJOWNIK", maxLevel: "" },
      { profName: "ŁOWCA", maxLevel: "" },
      { profName: "GWARDZISTA", maxLevel: "" },
      { profName: "BARBARZYŃCA", maxLevel: "" },
      { profName: "RYCERZ", maxLevel: "" },
      { profName: "PALADYN", maxLevel: "" },
      { profName: "CZARNY RYCERZ", maxLevel: "" },
      { profName: "ZŁODZIEJ", maxLevel: "" },
      { profName: "ZABÓJCA", maxLevel: "" },
      { profName: "KUPIEC", maxLevel: "" },
      { profName: "KAPŁAN", maxLevel: "" },
      { profName: "DRUID", maxLevel: "" },
      { profName: "ASTROLOG", maxLevel: "" },
      { profName: "PÓŁBÓG", maxLevel: "" },
      { profName: "MAG", maxLevel: "" },
      { profName: "CZARNOKSIĘŻNIK", maxLevel: "" },
      { profName: "ILUZJONISTA", maxLevel: "" },
      { profName: "ALCHEMIK", maxLevel: "" },
    ],

    stats: {
      male: {
        ŻYW: 100,
        SF: 50,
        ZR: 35,
        SZ: 25,
        INT: 60,
        MD: 70,
        UM: 0,
        CH: 40,
        PR: 20,
        WI: 10,
        ZW: 0,
        O: 0,
        W: 0,
      },
      female: {
        ŻYW: 90,
        SF: 40,
        ZR: 35,
        SZ: 25,
        INT: 60,
        MD: 70,
        UM: 0,
        CH: 40,
        PR: 40,
        WI: 10,
        ZW: 0,
        O: 0,
        W: 0,
      },
    },
    description:
      "- +5 pkt. do biegłości w mieczach, lancach, kopiach, kuszach, włóczniach i rapierach;\n- samouzdrowienie (czyli automatyczne odzyskiwanie punktów Wytrzymałości utraconych w wyniku odniesionych obrażeń) 2 pkt. obrażeń po każdych 8 godzinach wypoczynku;",
  },
  {
    id: "div_race2",
    type: "checkbox",
    raceName: "Półelfy",
    class: "race2 checkbox_container",
    availableProfessions: [
      { profName: "WOJOWNIK", maxLevel: "" },
      { profName: "ŁOWCA", maxLevel: "" },
      { profName: "GWARDZISTA", maxLevel: "" },
      { profName: "BARBARZYŃCA", maxLevel: "10 POZ" },
      { profName: "RYCERZ", maxLevel: "" },
      { profName: "PALADYN", maxLevel: "" },
      { profName: "CZARNY RYCERZ", maxLevel: "" },
      { profName: "ZŁODZIEJ", maxLevel: "" },
      { profName: "ZABÓJCA", maxLevel: "" },
      { profName: "KUPIEC", maxLevel: "15 POZ" },
      { profName: "KAPŁAN", maxLevel: "" },
      { profName: "DRUID", maxLevel: "" },

      { profName: "PÓŁBÓG", maxLevel: "" },
      { profName: "MAG", maxLevel: "" },
      { profName: "CZARNOKSIĘŻNIK", maxLevel: "" },
      { profName: "ILUZJONISTA", maxLevel: "10 POZ" },
      { profName: "ALCHEMIK", maxLevel: "15 POZ" },
    ],

    stats: {
      male: {
        ŻYW: 90,
        SF: 40,
        ZR: 40,
        SZ: 35,
        INT: 70,
        MD: 60,
        UM: 45,
        CH: 35,
        PR: 30,
        WI: 0,
        ZW: 0,
        O: 0,
        W: 0,
      },
      female: {
        ŻYW: 80,
        SF: 40,
        ZR: 40,
        SZ: 40,
        INT: 75,
        MD: 55,
        UM: 45,
        CH: 35,
        PR: 45,
        WI: 0,
        ZW: 0,
        O: 0,
        W: 0,
      },
    },
    description:
      "- 10 pkt. do biegłości w mieczach oraz 5 pkt. w łukach. włóczniach i lancach;\n- infrawizja (zdolność widzenia w naturalnych ciemnościach) o zasięgu równym 1/10 SZ (metrów);\n- samouzdrowienie 1 pkt. obrażeń po 8 godzinach wypoczynku;",
  },
  {
    id: "div_race3",
    type: "checkbox",
    raceName: "Elfy",
    class: "race3 checkbox_container",
    availableProfessions: [
      { profName: "WOJOWNIK", maxLevel: "" },
      { profName: "ŁOWCA", maxLevel: "" },
      { profName: "GWARDZISTA", maxLevel: "15 POZ" },

      { profName: "RYCERZ", maxLevel: "" },
      { profName: "PALADYN", maxLevel: "" },
      { profName: "CZARNY RYCERZ", maxLevel: "" },
      { profName: "ZŁODZIEJ", maxLevel: "" },
      { profName: "ZABÓJCA", maxLevel: "" },
      { profName: "KUPIEC", maxLevel: "10 POZ" },
      { profName: "KAPŁAN", maxLevel: "15 POZ" },
      { profName: "DRUID", maxLevel: "" },

      { profName: "PÓŁBÓG", maxLevel: "" },
      { profName: "MAG", maxLevel: "" },
    ],

    stats: {
      male: {
        ŻYW: 80,
        SF: 30,
        ZR: 50,
        SZ: 40,
        INT: 80,
        MD: 60,
        UM: 50,
        CH: 40,
        PR: 50,
        WI: 0,
        ZW: 0,
        O: 0,
        W: 0,
      },
      female: {
        ŻYW: 65,
        SF: 25,
        ZR: 50,
        SZ: 45,
        INT: 80,
        MD: 50,
        UM: 40,
        CH: 40,
        PR: 60,
        WI: 0,
        ZW: 0,
        O: 0,
        W: 0,
      },
    },
    description:
      "- 10 pkt. do biegłości w mieczach i łukach (z wyjątkiem refleksyjnych) oraz 5 pkt. we włóczniach i sztyletach;\n- infrawizja o zasięgu równym 2/10 SZ;\n- dwukrotnie większy niż wynikający ze współczynników zasięg słuchu i wzroku;\n- samouzdrowienie 1 pkt. obrażeń po 8 godzinach wypoczynku;",
  },
  {
    id: "div_race4",
    type: "checkbox",
    raceName: "Półolbrzymy",
    class: "race4 checkbox_container",
    availableProfessions: [
      { profName: "WOJOWNIK", maxLevel: "" },
      { profName: "ŁOWCA", maxLevel: "" },
      { profName: "GWARDZISTA", maxLevel: "" },
      { profName: "BARBARZYŃCA", maxLevel: "" },
      { profName: "RYCERZ", maxLevel: "" },
      { profName: "PALADYN", maxLevel: "10 POZ" },
      { profName: "CZARNY RYCERZ", maxLevel: "" },
      { profName: "ZŁODZIEJ", maxLevel: "15 POZ" },
      { profName: "ZABÓJCA", maxLevel: "10 POZ" },
      { profName: "KUPIEC", maxLevel: "10 POZ" },
      { profName: "KAPŁAN", maxLevel: "10 POZ" },
      { profName: "DRUID", maxLevel: "15 POZ" },
      { profName: "ASTROLOG", maxLevel: "10 POZ" },
      { profName: "PÓŁBÓG", maxLevel: "" },

      { profName: "CZARNOKSIĘŻNIK", maxLevel: "15 POZ" },
      { profName: "ILUZJONISTA", maxLevel: "" },
    ],

    stats: {
      male: {
        ŻYW: 150,
        SF: 100,
        ZR: 10,
        SZ: 40,
        INT: 30,
        MD: 40,
        UM: 10,
        CH: 20,
        PR: 40,
        WI: 0,
        ZW: 0,
        O: 5,
        W: 20,
      },
      female: {
        ŻYW: 145,
        SF: 80,
        ZR: 20,
        SZ: 40,
        INT: 40,
        MD: 40,
        UM: 10,
        CH: 20,
        PR: 30,
        WI: 0,
        ZW: 0,
        O: 5,
        W: 20,
      },
    },
    description:
      "- 5 pkt. do biegłości w kamieniach, maczugach, pałach, młotach oraz w walce na pięści;\n- dodatkowa Obrona 5 pkt. i Wyparowania 20 pkt., wynikające z grubości skóry (wszelkich obrażeń odniesionych w wyniku każdego rodzaju ataku - kłutego, tnącego lub obuchowego);\n- samouzdrowienie 4 pkt. obrażeń po 8 godzinach wypoczynku;",
  },
  {
    id: "div_race5",
    type: "checkbox",
    raceName: "Półorki",
    class: "race5 checkbox_container",
    availableProfessions: [
      { profName: "WOJOWNIK", maxLevel: "" },
      { profName: "ŁOWCA", maxLevel: "" },
      { profName: "GWARDZISTA", maxLevel: "" },
      { profName: "BARBARZYŃCA", maxLevel: "" },
      { profName: "RYCERZ", maxLevel: "" },
      { profName: "PALADYN", maxLevel: "10 POZ" },
      { profName: "CZARNY RYCERZ", maxLevel: "" },
      { profName: "ZŁODZIEJ", maxLevel: "" },
      { profName: "ZABÓJCA", maxLevel: "" },
      { profName: "KUPIEC", maxLevel: "15 POZ" },
      { profName: "KAPŁAN", maxLevel: "" },

      { profName: "ASTROLOG", maxLevel: "10 POZ" },
      { profName: "PÓŁBÓG", maxLevel: "" },

      { profName: "CZARNOKSIĘŻNIK", maxLevel: "" },
      { profName: "ILUZJONISTA", maxLevel: "10 POZ" },
      { profName: "ALCHEMIK", maxLevel: "15 POZ" },
    ],

    stats: {
      male: {
        ŻYW: 120,
        SF: 70,
        ZR: 30,
        SZ: 30,
        INT: 45,
        MD: 55,
        UM: 35,
        CH: 15,
        PR: 10,
        WI: 0,
        ZW: 0,
        O: 0,
        W: 0,
      },
      female: {
        ŻYW: 115,
        SF: 70,
        ZR: 40,
        SZ: 40,
        INT: 55,
        MD: 30,
        UM: 30,
        CH: 15,
        PR: 20,
        WI: 0,
        ZW: 0,
        O: 0,
        W: 0,
      },
    },
    description:
      "- 10 pkt. do biegłości w szablach, łukach refleksyjnych oraz 5 pkt. w nożach\n- infrawizja (1/10 SZ);\n- samouzdrowienie 2 pkt. obrażeń po 8 godzinach wypoczynku;",
  },
  {
    id: "div_race6",
    type: "checkbox",
    raceName: "Krasnoludy",
    class: "race6 checkbox_container",
    availableProfessions: [
      { profName: "WOJOWNIK", maxLevel: "" },
      { profName: "ŁOWCA", maxLevel: "10 POZ" },
      { profName: "GWARDZISTA", maxLevel: "" },

      { profName: "ZŁODZIEJ", maxLevel: "15 POZ" },
      { profName: "ZABÓJCA", maxLevel: "10 POZ" },
      { profName: "KUPIEC", maxLevel: "" },
      { profName: "KAPŁAN", maxLevel: "15 POZ" },

      { profName: "ASTROLOG", maxLevel: "" },
    ],

    stats: {
      male: {
        ŻYW: 130,
        SF: 70,
        ZR: 20,
        SZ: 15,
        INT: 40,
        MD: 70,
        UM: 30,
        CH: 30,
        PR: 15,
        WI: 0,
        ZW: 0,
        O: 5,
        W: 20,
      },
      female: {
        ŻYW: 125,
        SF: 65,
        ZR: 20,
        SZ: 20,
        INT: 45,
        MD: 75,
        UM: 25,
        CH: 20,
        PR: 15,
        WI: 0,
        ZW: 0,
        O: 5,
        W: 20,
      },
    },
    description:
      "- 10 pkt. do biegłości w toporach oraz 5 pkt. w kuszach, młotach, oskardach i sztyletach;\n- infrawizja (2/10 SZ);\n- dodatkowa Obrona 5 pkt. i Wyparowania 20 pkt.;\n- samouzdrowienie 3 pkt. obrażeń po 8 godzinach wypoczynku;",
  },
  {
    id: "div_race7",
    type: "checkbox",
    raceName: "Gnomy",
    class: "race7 checkbox_container",
    availableProfessions: [
      { profName: "WOJOWNIK", maxLevel: "15 POZ" },
      { profName: "ŁOWCA", maxLevel: "10 POZ" },
      { profName: "GWARDZISTA", maxLevel: "15 POZ" },

      { profName: "ZŁODZIEJ", maxLevel: "" },

      { profName: "KUPIEC", maxLevel: "" },
      { profName: "KAPŁAN", maxLevel: "" },
      { profName: "DRUID", maxLevel: "15 POZ" },
      { profName: "ASTROLOG", maxLevel: "" },
      { profName: "PÓŁBÓG", maxLevel: "" },

      { profName: "ILUZJONISTA", maxLevel: "" },
      { profName: "ALCHEMIK", maxLevel: "15 POZ" },
    ],

    stats: {
      male: {
        ŻYW: 100,
        SF: 50,
        ZR: 40,
        SZ: 15,
        INT: 80,
        MD: 80,
        UM: 40,
        CH: 15,
        PR: 25,
        WI: 0,
        ZW: 0,
        O: 2,
        W: 10,
      },
      female: {
        ŻYW: 80,
        SF: 40,
        ZR: 40,
        SZ: 25,
        INT: 70,
        MD: 80,
        UM: 45,
        CH: 15,
        PR: 30,
        WI: 0,
        ZW: 0,
        O: 2,
        W: 10,
      },
    },
    description:
      "- 10 pkt. do biegłości w młotach i toporach oraz 5 pkt. w krótkich mieczach;\n- infrawizja (2/10 SZ);\n- dodatkowa Obrona 2pkt. i Wyparowania 10 pkt.;\n- samouzdrowienie 3 pkt. obrażeń po 8 godzinach wypoczynku;",
  },
  {
    id: "div_race8",
    type: "checkbox",
    raceName: "Hobbici",
    class: "race8 checkbox_container",
    availableProfessions: [
      { profName: "WOJOWNIK", maxLevel: "15 POZ" },
      { profName: "ŁOWCA", maxLevel: "10 POZ" },

      { profName: "ZŁODZIEJ", maxLevel: "" },

      { profName: "KUPIEC", maxLevel: "" },
      { profName: "KAPŁAN", maxLevel: "10 POZ" },
      { profName: "DRUID", maxLevel: "15 POZ" },
      { profName: "ASTROLOG", maxLevel: "10 POZ" },
      { profName: "PÓŁBÓG", maxLevel: "" },

      { profName: "ILUZJONISTA", maxLevel: "10 POZ" },
    ],

    stats: {
      male: {
        ŻYW: 70,
        SF: 25,
        ZR: 60,
        SZ: 25,
        INT: 80,
        MD: 70,
        UM: 35,
        CH: 20,
        PR: 15,
        WI: 0,
        ZW: 0,
        O: 5,
        W: 20,
      },
      female: {
        ŻYW: 65,
        SF: 20,
        ZR: 60,
        SZ: 25,
        INT: 80,
        MD: 70,
        UM: 35,
        CH: 20,
        PR: 35,
        WI: 0,
        ZW: 0,
        O: 5,
        W: 20,
      },
    },
    description:
      "- 10 pkt. do biegłości w kamieniach oraz 5 pkt. w krótkich łukach, sztyletach i krótkich mieczach;\n- dodatkowa Obrona 5 pkt. i Wyparowania 20 pkt.;\n- samouzdrowienie 3 pkt. obrażeń po 8 godzinach wypoczynku;",
  },
  {
    id: "div_race9",
    type: "checkbox",
    raceName: "Reptilioni",
    class: "race9 checkbox_container",
    availableProfessions: [
      { profName: "WOJOWNIK", maxLevel: "" },
      { profName: "ŁOWCA", maxLevel: "" },
      { profName: "GWARDZISTA", maxLevel: "" },

      { profName: "RYCERZ", maxLevel: "" },
      { profName: "PALADYN", maxLevel: "" },

      { profName: "ZABÓJCA", maxLevel: "" },
      { profName: "KUPIEC", maxLevel: "10 POZ" },
      { profName: "KAPŁAN", maxLevel: "" },

      { profName: "ASTROLOG", maxLevel: "" },
      { profName: "PÓŁBÓG", maxLevel: "" },
      { profName: "MAG", maxLevel: "10 POZ" },

      { profName: "ILUZJONISTA", maxLevel: "10 POZ" },
      { profName: "ALCHEMIK", maxLevel: "10 POZ" },
    ],

    stats: {
      male: {
        ŻYW: 180,
        SF: 50,
        ZR: 20,
        SZ: 35,
        INT: 35,
        MD: 50,
        UM: 30,
        CH: 15,
        PR: 10,
        WI: 0,
        ZW: 0,
        O: 20,
        W: 60,
      },
      female: {
        ŻYW: 180,
        SF: 45,
        ZR: 25,
        SZ: 35,
        INT: 30,
        MD: 50,
        UM: 30,
        CH: 15,
        PR: 10,
        WI: 0,
        ZW: 0,
        O: 20,
        W: 60,
      },
    },
    description:
      "- 10 pkt. do biegłości w toporomieczach i w ataku pazurami oraz 5 pkt. w mieczach i kuszach;\n- nie mogą nosić smoczych skór i zbroi o ograniczeniach większych niż 1/2 ZR, 1/2 SZ;\n- dodatkowa Obrona 20 pkt. i Wyparowania 60 pki.;\n- samouzdrowienie 5 pkt. obrażeń po 8 godzinach wypoczynku;",
  },
];
