export const abilitiesData = (k100buttonResult) => {
  const abilitie = {
    abilitieName: "",
    abilitieDescription: "",
    statsModifier: 0,
    n: 0,
    k: 0,
  };

  if (k100buttonResult >= 1 && k100buttonResult < 3) {
    abilitie.abilitieName = "karzeł";
    abilitie.abilitieDescription =
      "wzrost postaci jest mniejszy od minimalnego wzrostu jego rasy o 20 + k10 cm (patrz punkt V oraz tabela V.a) konsekwencją tego jest zmniejszenie SZ postaci o połowę tej różnicy";
  } else if (k100buttonResult >= 3 && k100buttonResult < 5) {
    abilitie.abilitieName = "karzeł";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 5 && k100buttonResult < 7) {
    abilitie.abilitieName = "kulawy";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 7 && k100buttonResult < 9) {
    abilitie.abilitieName = "platfus";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 9 && k100buttonResult < 11) {
    abilitie.abilitieName = "zezowaty";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 11 && k100buttonResult < 13) {
    abilitie.abilitieName = "garbaty";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 13 && k100buttonResult < 15) {
    abilitie.abilitieName = "niepłodny";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 15 && k100buttonResult < 17) {
    abilitie.abilitieName = "jednoręki";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 17 && k100buttonResult < 19) {
    abilitie.abilitieName = "flegmatyk";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 19 && k100buttonResult < 21) {
    abilitie.abilitieName = "krótkowidz";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 21 && k100buttonResult < 23) {
    abilitie.abilitieName = "dalekowidz";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 23 && k100buttonResult < 25) {
    abilitie.abilitieName = "jąkała";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 25 && k100buttonResult < 27) {
    abilitie.abilitieName = "obżartuch";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 27 && k100buttonResult < 29) {
    abilitie.abilitieName = "szpetny";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 29 && k100buttonResult < 31) {
    abilitie.abilitieName = "śpioch";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 31 && k100buttonResult < 33) {
    abilitie.abilitieName = "pryszczaty";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 33 && k100buttonResult < 35) {
    abilitie.abilitieName = "alergik";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 35 && k100buttonResult < 37) {
    abilitie.abilitieName = "dotknięty amnezją";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 37 && k100buttonResult < 39) {
    abilitie.abilitieName = "jednooki";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 39 && k100buttonResult < 41) {
    abilitie.abilitieName = "cierpiący na klaustrofobię";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 41 && k100buttonResult < 43) {
    abilitie.abilitieName = "cierpiący na lęk wysokości";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 43 && k100buttonResult < 45) {
    abilitie.abilitieName = "debil";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 45 && k100buttonResult < 47) {
    abilitie.abilitieName = "nadwrazliwy na magię";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 47 && k100buttonResult < 49) {
    abilitie.abilitieName = "sodomita";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 49 && k100buttonResult < 51) {
    abilitie.abilitieName = "nekrofil";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 51 && k100buttonResult < 53) {
    abilitie.abilitieName = "biseksualista";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 53 && k100buttonResult < 55) {
    abilitie.abilitieName = "homoseksualista";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 55 && k100buttonResult < 57) {
    abilitie.abilitieName = "masochista";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 57 && k100buttonResult < 59) {
    abilitie.abilitieName = "sadysta";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 59 && k100buttonResult < 61) {
    abilitie.abilitieName = "złośliwiec";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 61 && k100buttonResult < 63) {
    abilitie.abilitieName = "zgrywus";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 63 && k100buttonResult < 65) {
    abilitie.abilitieName = "skąpiec";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 65 && k100buttonResult < 67) {
    abilitie.abilitieName = "rozrzutnik";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 67 && k100buttonResult < 69) {
    abilitie.abilitieName = "zarozumialec";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 69 && k100buttonResult < 71) {
    abilitie.abilitieName = "kłamca";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 71 && k100buttonResult < 73) {
    abilitie.abilitieName = "zachłanny";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 73 && k100buttonResult < 75) {
    abilitie.abilitieName = "pechowiec";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 75 && k100buttonResult < 77) {
    abilitie.abilitieName = "samotnik";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 77 && k100buttonResult < 79) {
    abilitie.abilitieName = "bezlitosny";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 79 && k100buttonResult < 81) {
    abilitie.abilitieName = "ryzykant";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 81 && k100buttonResult < 83) {
    abilitie.abilitieName = "hazardzista";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 83 && k100buttonResult < 85) {
    abilitie.abilitieName = "alkoholik";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 85 && k100buttonResult < 87) {
    abilitie.abilitieName = "nerwus";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 87 && k100buttonResult < 89) {
    abilitie.abilitieName = "tchórz";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 89 && k100buttonResult < 91) {
    abilitie.abilitieName = "lizus";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 91 && k100buttonResult < 93) {
    abilitie.abilitieName = "brudas";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 93 && k100buttonResult < 95) {
    abilitie.abilitieName = "podrywacz";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 95 && k100buttonResult < 97) {
    abilitie.abilitieName = "gluchy";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 97 && k100buttonResult < 99) {
    abilitie.abilitieName = "głupiec";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 99 && k100buttonResult < 101) {
    abilitie.abilitieName = "arcyułomność";
    abilitie.abilitieDescription =
      "zależna od MG, a powstała poprzez wymieszanie sie kilku ułoności";
  }

  return abilitie;
};
