export const abilitiesData = (k100buttonResult) => {
  const abilitie = {
    abilitieName: "",
    abilitieDescription: "",
    statsModifierKey: "",
    statsModifier: 0,
    n: 0,
    k: 0,
  };

  if (k100buttonResult >= 1 && k100buttonResult < 3) {
    abilitie.abilitieName = "twardziel";
    abilitie.statsModifierKey = "ŻYW";
    abilitie.abilitieDescription =
      "wzrost postaci jest mniejszy od minimalnego wzrostu jego rasy o 20 + k10 cm (patrz punkt V oraz tabela V.a) konsekwencją tego jest zmniejszenie SZ postaci o połowę tej różnicy";
  } else if (k100buttonResult >= 3 && k100buttonResult < 5) {
    abilitie.abilitieName = "siłacz";
    abilitie.statsModifierKey = "SF";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 5 && k100buttonResult < 7) {
    abilitie.abilitieName = "akrobata";
    abilitie.statsModifierKey = "ZR";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 7 && k100buttonResult < 9) {
    abilitie.abilitieName = "szybki";
    abilitie.statsModifierKey = "SZ";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 9 && k100buttonResult < 11) {
    abilitie.abilitieName = "geniusz";
    abilitie.statsModifierKey = "INT";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 11 && k100buttonResult < 13) {
    abilitie.abilitieName = "mędzrzec";
    abilitie.statsModifierKey = "MD";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 13 && k100buttonResult < 15) {
    abilitie.abilitieName = "magik";
    abilitie.statsModifierKey = "UM";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 15 && k100buttonResult < 17) {
    abilitie.abilitieName = "fanatyk";
    abilitie.statsModifierKey = "WI";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 17 && k100buttonResult < 19) {
    abilitie.abilitieName = "ulubieniec bogów";
    abilitie.statsModifierKey = "ZW";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 19 && k100buttonResult < 21) {
    abilitie.abilitieName = "elokwentny";
    abilitie.statsModifierKey = "CH";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 21 && k100buttonResult < 23) {
    abilitie.abilitieName = "piękniś";
    abilitie.statsModifierKey = "PR";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 23 && k100buttonResult < 25) {
    abilitie.abilitieName = "poliglota";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 25 && k100buttonResult < 27) {
    abilitie.abilitieName = "długowieczny";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 27 && k100buttonResult < 29) {
    abilitie.abilitieName = "fechmistrz";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 29 && k100buttonResult < 31) {
    abilitie.abilitieName = "odporny na iluzję (odp. nr 1)";
    abilitie.statsModifierKey = "Odp1";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 31 && k100buttonResult < 33) {
    abilitie.abilitieName = "odporny na sugestię (odp. nr 2)";
    abilitie.statsModifierKey = "Odp2";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 33 && k100buttonResult < 35) {
    abilitie.abilitieName = "odporny na zaklęcia (odp. nr 3)";
    abilitie.statsModifierKey = "Odp3";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 35 && k100buttonResult < 37) {
    abilitie.abilitieName = "odporny na szok (odp. nr 4)";
    abilitie.statsModifierKey = "Odp4";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 37 && k100buttonResult < 39) {
    abilitie.abilitieName = "odporny na magię (odp. nr 5)";
    abilitie.statsModifierKey = "Odp5";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 39 && k100buttonResult < 41) {
    abilitie.abilitieName = "odporny na trucizny (odp. nr 6)";
    abilitie.statsModifierKey = "Odp6";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 41 && k100buttonResult < 43) {
    abilitie.abilitieName = "odporny na gazy (odp. nr 7)";
    abilitie.statsModifierKey = "Odp7";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 43 && k100buttonResult < 45) {
    abilitie.abilitieName = "odporny na wszelkie czynniki fizyczne (odp. nr 8)";
    abilitie.statsModifierKey = "Odp8";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 45 && k100buttonResult < 47) {
    abilitie.abilitieName = "odporny na magnetyzm (odp. nr 9)";
    abilitie.statsModifierKey = "Odp9";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 47 && k100buttonResult < 49) {
    abilitie.abilitieName = "odporny na polimorfię (odp. nr 10)";
    abilitie.statsModifierKey = "Odp10";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 49 && k100buttonResult < 51) {
    abilitie.abilitieName = "odporny na głód";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 51 && k100buttonResult < 53) {
    abilitie.abilitieName = "odporny na pragnienie";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 53 && k100buttonResult < 55) {
    abilitie.abilitieName = "odporny na chłód";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 55 && k100buttonResult < 57) {
    abilitie.abilitieName = "odporny na gorąco";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 57 && k100buttonResult < 59) {
    abilitie.abilitieName = "odporny na zmęczenie";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 59 && k100buttonResult < 61) {
    abilitie.abilitieName = "odporny na choroby";
    abilitie.statsModifierKey = "Odp6";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 61 && k100buttonResult < 63) {
    abilitie.abilitieName = "odporny na przemiany";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 63 && k100buttonResult < 65) {
    abilitie.abilitieName = "widzenie nocą";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 65 && k100buttonResult < 67) {
    abilitie.abilitieName = "przenikliwy wzrok";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 67 && k100buttonResult < 69) {
    abilitie.abilitieName = "nadzwyczajny słuch";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 69 && k100buttonResult < 71) {
    abilitie.abilitieName = "nadzwyczajny węch";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 71 && k100buttonResult < 73) {
    abilitie.abilitieName = "sokoli wzrok";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 73 && k100buttonResult < 75) {
    abilitie.abilitieName = "znachor";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 75 && k100buttonResult < 77) {
    abilitie.abilitieName = "znawca Dawnej Mowy";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 77 && k100buttonResult < 79) {
    abilitie.abilitieName = "obdarzony zdolnością regeneracji";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 79 && k100buttonResult < 81) {
    abilitie.abilitieName = "potrzebujący mniej snu";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 81 && k100buttonResult < 83) {
    abilitie.abilitieName = "telekinetyk";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 83 && k100buttonResult < 85) {
    abilitie.abilitieName = "telepata";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 85 && k100buttonResult < 87) {
    abilitie.abilitieName = "wieszcz";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 87 && k100buttonResult < 89) {
    abilitie.abilitieName = "hipnotyzer";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 89 && k100buttonResult < 91) {
    abilitie.abilitieName = "intuicjonista";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 91 && k100buttonResult < 93) {
    abilitie.abilitieName = "imitator";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 93 && k100buttonResult < 95) {
    abilitie.abilitieName = "orator";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 95 && k100buttonResult < 97) {
    abilitie.abilitieName = "wyczuwając zachwianie równowagi sił";
    abilitie.abilitieDescription = "";
  } else if (k100buttonResult >= 97 && k100buttonResult < 99) {
    abilitie.abilitieName = "szczęściarz";
    abilitie.abilitieDescription = "";
  } else if ((k100buttonResult === 99)) {
    abilitie.abilitieName = "inna zdolność";
    abilitie.abilitieDescription =
      "zależna od MG, a powstała poprzez wymieszanie sie kilku ułoności";
  } else if ((k100buttonResult === 100)) {
    abilitie.abilitieName = "bołogosławieństwo obfitości";
    abilitie.abilitieDescription =
      "zależna od MG, a powstała poprzez wymieszanie sie kilku ułoności";
  }

  return abilitie;
};
