export const disabilitiesData = (k100buttonResult) => {
  const disabilitie = {
    disabilitieName: "",
    disabilitieDescription: "",
    statsModifier: 0,
    n: 0,
    k: 0,
  };

  if (k100buttonResult >= 1 && k100buttonResult < 3) {
    disabilitie.disabilitieName = "karzeł";
    disabilitie.disabilitieDescription =
      "wzrost postaci jest mniejszy od minimalnego wzrostu jego rasy o 20 + k10 cm (patrz punkt V oraz tabela V.a) konsekwencją tego jest zmniejszenie SZ postaci o połowę tej różnicy";
  } else if (k100buttonResult >= 3 && k100buttonResult < 5) {
    disabilitie.disabilitieName = "karzeł";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 5 && k100buttonResult < 7) {
    disabilitie.disabilitieName = "kulawy";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 7 && k100buttonResult < 9) {
    disabilitie.disabilitieName = "platfus";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 9 && k100buttonResult < 11) {
    disabilitie.disabilitieName = "zezowaty";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 11 && k100buttonResult < 13) {
    disabilitie.disabilitieName = "garbaty";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 13 && k100buttonResult < 15) {
    disabilitie.disabilitieName = "niepłodny";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 15 && k100buttonResult < 17) {
    disabilitie.disabilitieName = "jednoręki";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 17 && k100buttonResult < 19) {
    disabilitie.disabilitieName = "flegmatyk";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 19 && k100buttonResult < 21) {
    disabilitie.disabilitieName = "krótkowidz";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 21 && k100buttonResult < 23) {
    disabilitie.disabilitieName = "dalekowidz";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 23 && k100buttonResult < 25) {
    disabilitie.disabilitieName = "jąkała";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 25 && k100buttonResult < 27) {
    disabilitie.disabilitieName = "obżartuch";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 27 && k100buttonResult < 29) {
    disabilitie.disabilitieName = "szpetny";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 29 && k100buttonResult < 31) {
    disabilitie.disabilitieName = "śpioch";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 31 && k100buttonResult < 33) {
    disabilitie.disabilitieName = "pryszczaty";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 33 && k100buttonResult < 35) {
    disabilitie.disabilitieName = "alergik";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 35 && k100buttonResult < 37) {
    disabilitie.disabilitieName = "dotknięty amnezją";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 37 && k100buttonResult < 39) {
    disabilitie.disabilitieName = "jednooki";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 39 && k100buttonResult < 41) {
    disabilitie.disabilitieName = "cierpiący na klaustrofobię";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 41 && k100buttonResult < 43) {
    disabilitie.disabilitieName = "cierpiący na lęk wysokości";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 43 && k100buttonResult < 45) {
    disabilitie.disabilitieName = "debil";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 45 && k100buttonResult < 47) {
    disabilitie.disabilitieName = "nadwrazliwy na magię";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 47 && k100buttonResult < 49) {
    disabilitie.disabilitieName = "sodomita";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 49 && k100buttonResult < 51) {
    disabilitie.disabilitieName = "nekrofil";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 51 && k100buttonResult < 53) {
    disabilitie.disabilitieName = "biseksualista";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 53 && k100buttonResult < 55) {
    disabilitie.disabilitieName = "homoseksualista";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 55 && k100buttonResult < 57) {
    disabilitie.disabilitieName = "masochista";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 57 && k100buttonResult < 59) {
    disabilitie.disabilitieName = "sadysta";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 59 && k100buttonResult < 61) {
    disabilitie.disabilitieName = "złośliwiec";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 61 && k100buttonResult < 63) {
    disabilitie.disabilitieName = "zgrywus";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 63 && k100buttonResult < 65) {
    disabilitie.disabilitieName = "skąpiec";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 65 && k100buttonResult < 67) {
    disabilitie.disabilitieName = "rozrzutnik";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 67 && k100buttonResult < 69) {
    disabilitie.disabilitieName = "zarozumialec";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 69 && k100buttonResult < 71) {
    disabilitie.disabilitieName = "kłamca";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 71 && k100buttonResult < 73) {
    disabilitie.disabilitieName = "zachłanny";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 73 && k100buttonResult < 75) {
    disabilitie.disabilitieName = "pechowiec";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 75 && k100buttonResult < 77) {
    disabilitie.disabilitieName = "samotnik";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 77 && k100buttonResult < 79) {
    disabilitie.disabilitieName = "bezlitosny";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 79 && k100buttonResult < 81) {
    disabilitie.disabilitieName = "ryzykant";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 81 && k100buttonResult < 83) {
    disabilitie.disabilitieName = "hazardzista";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 83 && k100buttonResult < 85) {
    disabilitie.disabilitieName = "alkoholik";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 85 && k100buttonResult < 87) {
    disabilitie.disabilitieName = "nerwus";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 87 && k100buttonResult < 89) {
    disabilitie.disabilitieName = "tchórz";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 89 && k100buttonResult < 91) {
    disabilitie.disabilitieName = "lizus";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 91 && k100buttonResult < 93) {
    disabilitie.disabilitieName = "brudas";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 93 && k100buttonResult < 95) {
    disabilitie.disabilitieName = "podrywacz";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 95 && k100buttonResult < 97) {
    disabilitie.disabilitieName = "gluchy";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 97 && k100buttonResult < 99) {
    disabilitie.disabilitieName = "głupiec";
    disabilitie.disabilitieDescription = "";
  } else if (k100buttonResult >= 99 && k100buttonResult < 101) {
    disabilitie.disabilitieName = "arcyułomność";
    disabilitie.disabilitieDescription =
      "zależna od MG, a powstała poprzez wymieszanie sie kilku ułoności";
  }

  return disabilitie;
};
