const chp4_professions = [
  ["WOJOWNIK", "ŁOWCA", "GWARDZISTA", "BARBARZYŃCA"],
  ["RYCERZ", "PALADYN", "CZARNY RYCERZ"],
  ["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"],
  ["KAPŁAN", "DRUID", "ASTROLOG", "PÓŁBÓG"],
  ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
];

export const chp4_professionsList = [
  {
    id: "prof1",
    profName: "WOJOWNIK",
    castName: "ŻOŁNIERSKA",
    combiningProfessions: [
      ["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"],
      ["KAPŁAN", "DRUID", "ASTROLOG"],
      ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {
      ŻYW: 10,
      SF: 20,
      ZR: 10,
      SZ: 10,
      INT: 0,
      MD: 10,
      UM: 0,
      CH: 0,
      PR: 0,
      WI: 0,
      ZW: 0,

      k10_ŻYW: true,
      k10_SF: true,
      k10_ZR: true,
      k10_SZ: true,
      k10_INT: false,
      k10_MD: true,
      k10_UM: false,
      k10_CH: true,
      k10_PR: true,
      k10_WI: false,
      k10_ZW: false,

      Odp1: 0,
      Odp2: 10,
      Odp3: 0,
      Odp4: 10,
      Odp5: 0,

      Odp6: 10,
      Odp7: 10,
      Odp8: 10,
      Odp9: 10,
      Odp10: 0,

      k10_Odp1: false,
      k10_Odp2: true,
      k10_Odp3: false,
      k10_Odp4: true,
      k10_Odp5: false,

      k10_Odp6: true,
      k10_Odp7: true,
      k10_Odp8: true,
      k10_Odp9: true,
      k10_Odp10: false,
    },
  },
  {
    id: "prof2",
    profName: "ŁOWCA",
    castName: "ŻOŁNIERSKA",
    combiningProfessions: [["KUPIEC"], ["KAPŁAN", "DRUID"], ["MAG"]],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {
      ŻYW: 10,
      SF: 10,
      ZR: 10,
      SZ: 10,
      INT: 0,
      MD: 10,
      UM: 0,
      CH: 10,
      PR: 10,
      WI: 10,
      ZW: 0,

      k10_ŻYW: true,
      k10_SF: true,
      k10_ZR: true,
      k10_SZ: true,
      k10_INT: false,
      k10_MD: true,
      k10_UM: true,
      k10_CH: true,
      k10_PR: true,
      k10_WI: true,
      k10_ZW: false,

      Odp1: 0,
      Odp2: 10,
      Odp3: 10,
      Odp4: 0,
      Odp5: 0,

      Odp6: 10,
      Odp7: 10,
      Odp8: 10,
      Odp9: 0,
      Odp10: 10,

      k10_Odp1: false,
      k10_Odp2: true,
      k10_Odp3: true,
      k10_Odp4: false,
      k10_Odp5: false,

      k10_Odp6: true,
      k10_Odp7: true,
      k10_Odp8: true,
      k10_Odp9: false,
      k10_Odp10: true,
    },
  },
  {
    id: "prof3",
    profName: "GWARDZISTA",
    castName: "ŻOŁNIERSKA",
    combiningProfessions: [["ZABÓJCA"], ["KAPŁAN"]],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {
      ŻYW: 0,
      SF: 10,
      ZR: 0,
      SZ: 20,
      INT: 0,
      MD: 0,
      UM: 0,
      CH: 10,
      PR: 20,
      WI: 0,
      ZW: 0,

      k10_ŻYW: true,
      k10_SF: true,
      k10_ZR: true,
      k10_SZ: true,
      k10_INT: false,
      k10_MD: false,
      k10_UM: false,
      k10_CH: true,
      k10_PR: true,
      k10_WI: true,
      k10_ZW: false,

      Odp1: 10,
      Odp2: 20,
      Odp3: 10,
      Odp4: 0,
      Odp5: 0,

      Odp6: 0,
      Odp7: 10,
      Odp8: 10,
      Odp9: 0,
      Odp10: 0,

      k10_Odp1: true,
      k10_Odp2: true,
      k10_Odp3: true,
      k10_Odp4: false,
      k10_Odp5: false,

      k10_Odp6: false,
      k10_Odp7: true,
      k10_Odp8: true,
      k10_Odp9: false,
      k10_Odp10: false,
    },
  },
  {
    id: "prof4",
    profName: "BARBARZYŃCA",
    castName: "ŻOŁNIERSKA",
    combiningProfessions: [["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"], ["KAPŁAN"]],
    exeptionCombiningProfessions: [],
    character: [
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {
      ŻYW: 20,
      SF: 20,
      ZR: 20,
      SZ: 20,
      INT: 0,
      MD: 0,
      UM: 0,
      CH: 0,
      PR: 0,
      WI: 0,
      ZW: 0,

      k10_ŻYW: true,
      k10_SF: true,
      k10_ZR: true,
      k10_SZ: true,
      k10_INT: false,
      k10_MD: false,
      k10_UM: false,
      k10_CH: false,
      k10_PR: false,
      k10_WI: true,
      k10_ZW: false,

      Odp1: 0,
      Odp2: 0,
      Odp3: 0,
      Odp4: 10,
      Odp5: 10,

      Odp6: 10,
      Odp7: 10,
      Odp8: 10,
      Odp9: 0,
      Odp10: 10,

      k10_Odp1: false,
      k10_Odp2: false,
      k10_Odp3: false,
      k10_Odp4: true,
      k10_Odp5: true,

      k10_Odp6: true,
      k10_Odp7: true,
      k10_Odp8: true,
      k10_Odp9: false,
      k10_Odp10: true,
    },
  },
  {
    id: "prof5",
    profName: "RYCERZ",
    castName: "RYCERSKA",
    combiningProfessions: [["KAPŁAN"]],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
  {
    profName: "PALADYN",
    castName: "RYCERSKA",
    combiningProfessions: [["ASTROLOG"]],
    exeptionCombiningProfessions: [],
    character: ["praworządny-dobry"],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
  {
    profName: "CZARNY RYCERZ",
    castName: "RYCERSKA",
    combiningProfessions: [["KAPŁAN"]],
    exeptionCombiningProfessions: [],
    character: ["praworządny-zły"],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
  {
    profName: "ZŁODZIEJ",
    castName: "ZŁODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK", "BARBARZYŃCA"],
      ["KUPIEC"],
      ["KAPŁAN"],
      ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
  {
    profName: "ZABÓJCA",
    castName: "ZŁODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK", "GWARDZISTA", "BARBARZYŃCA"],

      ["KAPŁAN"],
      ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-neutralny",
      "praworządny-zły",

      "neutralny-neutralny",
      "neutralny-zły",

      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
  {
    profName: "KUPIEC",
    castName: "ZŁODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK", "GWARDZISTA", "BARBARZYŃCA"],

      ["ZŁODZIEJ", "ZABÓJCA"],
      ["KAPŁAN", "DRUID", "ASTROLOG"],
      ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
  {
    profName: "KAPŁAN",
    castName: "KAPŁAŃSKA",
    combiningProfessions: [
      ["WOJOWNIK", "ŁOWCA", "GWARDZISTA", "BARBARZYŃCA"],
      ["RYCERZ", "CZARNY RYCERZ"],
      ["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"],

      ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    etos: ["WOJENNY", "DUCHOWY"],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
  {
    profName: "DRUID",
    castName: "KAPŁAŃSKA",
    combiningProfessions: [["WOJOWNIK", "ŁOWCA"], ["MAG"]],
    exeptionCombiningProfessions: [],
    character: ["neutralny-dobry", "neutralny-neutralny", "neutralny-zły"],
    druidicCircle: [],
    
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
  {
    profName: "ASTROLOG",
    castName: "KAPŁAŃSKA",
    combiningProfessions: [
      ["WOJOWNIK"],
      ["RYCERZ", "PALADYN", "CZARNY RYCERZ"],
      ["KUPIEC"],
      ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
  {
    profName: "PÓŁBÓG",
    castName: "KAPŁAŃSKA",
    combiningProfessions: [],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
  {
    profName: "MAG",
    castName: "CZARODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK", "ŁOWCA"],
      ["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"],
      ["KAPŁAN", "DRUID", "ASTROLOG"],
      ["CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
  {
    profName: "CZARNOKSIĘŻNIK",
    castName: "CZARODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK"],

      ["ZABÓJCA", "KUPIEC"],
      ["KAPŁAN", "ASTROLOG"],
      ["MAG", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: ["praworządny-zły", "neutralny-zły", "chaotyczny-zły"],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
  {
    profName: "ILUZJONISTA",
    castName: "CZARODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK"],

      ["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"],
      ["KAPŁAN", "ASTROLOG", "PÓŁBÓG"],
      ["MAG", "CZARNOKSIĘŻNIK", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
  {
    profName: "ALCHEMIK",
    castName: "CZARODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK"],
      ["RYCERZ"],
      ["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"],
      ["KAPŁAN", "ASTROLOG"],
      ["MAG", "ILUZJONISTA", "CZARNOKSIĘŻNIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
    stats: {},
  },
];

export default chp4_professions;
