const chp4_professions = [
  ["WOJOWNIK", "ŁOWCA", "GWARDZISTA", "BARBARZYŃCA"],
  ["RYCERZ", "PALADYN", "CZARNY RYCERZ"],
  ["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"],
  ["KAPŁAN", "DRUID", "ASTROLOG", "PÓŁBÓG"],
  ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
];

export const chp4_professionsList = [
  {
    profName: "WOJOWNIK",
    castName: "ŻOŁNIERSKA",
    combiningProfessions: [
      ["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"],
      ["KAPŁAN", "DRUID", "ASTROLOG"],
      ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "ŁOWCA",
    castName: "ŻOŁNIERSKA",
    combiningProfessions: [["KUPIEC"], ["KAPŁAN", "DRUID"], ["MAG"]],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "GWARDZISTA",
    castName: "ŻOŁNIERSKA",
    combiningProfessions: [["ZABÓJCA"], ["KAPŁAN"]],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "BARBARZYŃCA",
    castName: "ŻOŁNIERSKA",
    combiningProfessions: [["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"], ["KAPŁAN"]],
    exeptionCombiningProfessions: [],
    character: [
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "RYCERZ",
    castName: "RYCERSKA",
    combiningProfessions: [["KAPŁAN"]],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "PALADYN",
    castName: "RYCERSKA",
    combiningProfessions: [["ASTROLOG"]],
    exeptionCombiningProfessions: [],
    character: ["praworządny-dobry"],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "CZARNY RYCERZ",
    castName: "RYCERSKA",
    combiningProfessions: [["KAPŁAN"]],
    exeptionCombiningProfessions: [],
    character: ["praworządny-zły"],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "ZŁODZIEJ",
    castName: "ZŁODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK", "BARBARZYŃCA"],
      ["KUPIEC"],
      ["KAPŁAN"],
      ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "ZABÓJCA",
    castName: "ZŁODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK", "GWARDZISTA", "BARBARZYŃCA"],

      ["KAPŁAN"],
      ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-neutralny",
      "praworządny-zły",

      "neutralny-neutralny",
      "neutralny-zły",

      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "KUPIEC",
    castName: "ZŁODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK", "GWARDZISTA", "BARBARZYŃCA"],

      ["ZŁODZIEJ", "ZABÓJCA"],
      ["KAPŁAN", "DRUID", "ASTROLOG"],
      ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "KAPŁAN",
    castName: "KAPŁAŃSKA",
    combiningProfessions: [
      ["WOJOWNIK", "ŁOWCA", "GWARDZISTA", "BARBARZYŃCA"],
      ["RYCERZ", "CZARNY RYCERZ"],
      ["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"],

      ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "DRUID",
    castName: "KAPŁAŃSKA",
    combiningProfessions: [["WOJOWNIK", "ŁOWCA"], ["MAG"]],
    exeptionCombiningProfessions: [],
    character: ["neutralny-dobry", "neutralny-neutralny", "neutralny-zły"],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "ASTROLOG",
    castName: "KAPŁAŃSKA",
    combiningProfessions: [
      ["WOJOWNIK"],
      ["RYCERZ", "PALADYN", "CZARNY RYCERZ"],
      ["KUPIEC"],
      ["MAG", "CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "PÓŁBÓG",
    castName: "KAPŁAŃSKA",
    combiningProfessions: [],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "MAG",
    castName: "CZARODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK", "ŁOWCA"],
      ["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"],
      ["KAPŁAN", "DRUID", "ASTROLOG"],
      ["CZARNOKSIĘŻNIK", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "CZARNOKSIĘŻNIK",
    castName: "CZARODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK"],

      ["ZABÓJCA", "KUPIEC"],
      ["KAPŁAN", "ASTROLOG"],
      ["MAG", "ILUZJONISTA", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: ["praworządny-zły", "neutralny-zły", "chaotyczny-zły"],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "ILUZJONISTA",
    castName: "CZARODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK"],

      ["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"],
      ["KAPŁAN", "ASTROLOG", "PÓŁBÓG"],
      ["MAG", "CZARNOKSIĘŻNIK", "ALCHEMIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
  {
    profName: "ALCHEMIK",
    castName: "CZARODZIEJSKA",
    combiningProfessions: [
      ["WOJOWNIK"],
      ["RYCERZ"],
      ["ZŁODZIEJ", "ZABÓJCA", "KUPIEC"],
      ["KAPŁAN", "ASTROLOG"],
      ["MAG", "ILUZJONISTA", "CZARNOKSIĘŻNIK"],
    ],
    exeptionCombiningProfessions: [],
    character: [
      "praworządny-dobry",
      "praworządny-neutralny",
      "praworządny-zły",
      "neutralny-dobry",
      "neutralny-neutralny",
      "neutralny-zły",
      "chaotyczny-dobry",
      "chaotyczny-neutralny",
      "chaotyczny-zły",
    ],
    usedWeapons: "",
    usedArmour: "",
    uesedMagic: "",
    formation: "",
  },
];






export default chp4_professions;
